package v2;


/**
 * This class was generated by a SmartGuide.
 * 
 */
 import java.awt.Event;
 import VideoGame.BenLogo;
public class AboutButton extends java.awt.Button {







/**
 * AboutButton constructor comment.
 */
public AboutButton() {
	super();
}
/**
 * AboutButton constructor comment.
 * @param label java.lang.String
 */
public AboutButton(String label) {
	super(label);
}
/**
 * This method was created by a SmartGuide.
 * @param e Event
 */
public boolean handleEvent(Event e) {
	if (e.id==1001){
		Thread logoThread = new Thread(new BenLogo(), "Who needs you?");
		logoThread.run();
}
	return super.handleEvent(e);
}
}
