package v2;


/**
 * This class was generated by a SmartGuide.
 * 
 */
 import java.awt.Color;
 import java.awt.Image;
 import java.awt.Graphics;
 import java.awt.image.ImageObserver;
public class Base extends City {
	private int _numberOfMissiles;
	private final int MISSILES_PER_BASE = 10;





/**
 * This method was created by a SmartGuide.
 * @param ai Image
 * @param di Image
 * @param g Graphics
 */
public Base (Image ai, Image di, Graphics g ) {
	super(ai, di, g);
	numberOfMissiles(MISSILES_PER_BASE);
}
/**
 * This method was created by a SmartGuide.
 */
public void destruct ( ) {
	numberOfMissiles(0);
	super.destruct();
}
/**
 * This method was created by a SmartGuide.
 */
public void displayNumberOfMissiles ( ) {
	graphics().setColor(Color.white);
	graphics().fillRect(0, 30, 100, 30);
	graphics().setColor(Color.black);
	graphics().drawString("Ammo:"+String.valueOf(numberOfMissiles()),0,40);
}
/**
 * This method was created by a SmartGuide.
 */
public void drawSelf (ImageObserver ia ) {
	displayNumberOfMissiles();
	boolean b = graphics().drawImage(image(), 4,0,ia);
}
/**
 * This method was created by a SmartGuide.
 * @return int
 */
public int numberOfMissiles() {
	return _numberOfMissiles;
}
/**
 * This method was created by a SmartGuide.
 * @param i int
 */
public void numberOfMissiles(int i) {
	_numberOfMissiles = i;
}
/**
 * This method was created by a SmartGuide.
 * @return boolean
 */
public boolean queryLaunchMissile() {
	if (numberOfMissiles() > 0){
		numberOfMissiles(numberOfMissiles() - 1);
		displayNumberOfMissiles();
		return true;
	}
	else {
		return false;
	}	
	

}
/**
 * This method was created by a SmartGuide.
 */
public void ressurect() {
	numberOfMissiles(10);
	super.ressurect();
}
}
