package v2;


/**
 * This class was generated by a SmartGuide.
 * 
 */
public class BlastInfo {
	boolean _nullToken;
	Explosion _explosion;

/**
 * This method was created by a SmartGuide.
 * @return v2.Explosion
 */
public Explosion explosion() {
	return _explosion;
}
/**
 * This method was created by a SmartGuide.
 * @param e v2.Explosion
 */
public void explosion(Explosion e) {
	_explosion =e;
}
/**
 * This method was created by a SmartGuide.
 * @return boolean
 */
public boolean nullToken() {
	return _nullToken;
}
/**
 * This method was created by a SmartGuide.
 * @param b boolean
 */
public void nullToken(boolean b) {
	_nullToken =b;
}
}
