package v2;


/**
 * This class was generated by a SmartGuide.
 * 
 */
 import java.awt.Image;
 import java.awt.Graphics;
  import java.awt.image.ImageObserver;
public class City extends VideoGame.Stationary {
	private Image aliveImage;
	private Image deadImage;
	private boolean _destroyed;





/**
 * This method was created by a SmartGuide.
 * @param ai java.awt.Image
 * @param di java.awt.Image
 * @param g java.awt.Graphics
 */
public City (Image ai, Image di, Graphics g) {
	graphics(g);
	aliveImage = ai;
	deadImage = di;
	image(ai);
}
/**
 * This method was created by a SmartGuide.
 * @return boolean
 */
public boolean destroyed() {
	return _destroyed;
}
/**
 * This method was created by a SmartGuide.
 * @param b boolean
 */
public void destroyed(boolean b) {
	_destroyed = b;
}
/**
 * This method was created by a SmartGuide.
 */
public void destruct ( ) {
	destroyed(true);
	image(deadImage);
	drawSelf(imageObserver());
}
/**
 * This method was created by a SmartGuide.
 */
public void ressurect() {
	destroyed(false);
	image(aliveImage);
	drawSelf(imageObserver());
}
}
