package v2;


/**
 * This class was generated by a SmartGuide.
 * 
 */
 import java.awt.*;
 import VideoGame.DynamicManagerI;
public class Explosion extends VideoGame.Transient {
	protected int _radius;
	protected boolean _waxing;
	final int MAXIMUM_RADIUS = 33;
	final int INCRIMENT = 3;
	protected MissileCommandManager _missileCommandManager;
	
	/**
	 * These variables are here to expedite
	 * inBlastArea calculations.
	 */
	private int maxX;
	private int maxY;
	private int minX;
	private int minY;







/**
 * This method was created by a SmartGuide.
 * @param x int
 * @param y int
 * @param gm GameManager
 */
public Explosion (int x, int y, MissileCommandManager mm) {
	missileCommandManager(mm);
	position(new Point(x,y));
	maxX = x+MAXIMUM_RADIUS;
	maxY = y+MAXIMUM_RADIUS;
	minX = x-MAXIMUM_RADIUS;
	minY = y-MAXIMUM_RADIUS;
  	graphics(graphics().create(minX, minY, MAXIMUM_RADIUS*2, MAXIMUM_RADIUS*2));
	duration(22);
	waxing(true);
	radius(0);
}
/**
 * This method was created by a SmartGuide.
 */
public void clearBlastArea ( ) {
	graphics().setColor(Color.white);
		int offSetFromULCorner = MAXIMUM_RADIUS - radius();
	 graphics().fillOval(offSetFromULCorner, offSetFromULCorner, diameter(), diameter());

}
/**
 * This method was created by a SmartGuide.
 */
public int diameter() {
	return _radius * 2;
}
/**
 * This method was created by a SmartGuide.
 */
public boolean inBlastArea (int x, int y ) {
/**
 * don't do the distance formula unless you have to.
 */
	if(inRectangle(x,y)){
			return radius() >= (Math.abs((x - position().x)^2 +(y - position().y)^2));
}	
else return false;
}
/**
 * This method was created by a SmartGuide.
 */
public boolean inRectangle (int x, int y ) {
 	if(minX < x) 
 		if(x< maxX)
 			if(minY < y)
 				return (y < maxY);
 	return false;
}
/**
 * This method was created by a SmartGuide.
 * @return v2.MissileCommandManager
 */
public MissileCommandManager missileCommandManager ( ) {
	return _missileCommandManager;
}
/**
 * This method was created by a SmartGuide.
 * @param m v2.MissileCommandManager
 */
public void missileCommandManager(MissileCommandManager m) {
	dynamicManagerI(m.dynamicManagerI());
	_missileCommandManager = m;
}
/**
 * This method was created by a SmartGuide.
 */
public void move ( ) {
	super.move();	
	if (waxing()) {
		wax();
	}
	else {  //must be waneing
		wane();
	}	
}
/**
 * This method was created by a SmartGuide.
 * @return int
 */
public int radius() {
	return _radius;
}
/**
 * This method was created by a SmartGuide.
 */
public void radius(int i) {
	_radius = i;
}
/**
 * This method was created by a SmartGuide.
 * @param dm VideoGame.DynamicManagerI
 */
public void remove() {
	missileCommandManager().removeExplosion(this);
	super.remove();
}
/**
 * This method was created by a SmartGuide.
 */
public void showBlast ( ) {
	graphics().setColor(Color.black);
  int offSetFromULCorner = MAXIMUM_RADIUS-radius();
	graphics().fillOval(offSetFromULCorner, offSetFromULCorner, diameter(), diameter());

}
/**
 * This method was created by a SmartGuide.
 */
public void wane() {
			clearBlastArea();
			radius(radius()-INCRIMENT);
			showBlast();
}
/**
 * This method was created by a SmartGuide.
 */
public void wax ( ) {
	radius(radius()+INCRIMENT);
	showBlast();
	if (radius() == MAXIMUM_RADIUS){
		waxing(false);
	}		
}
/**
 * This method was created by a SmartGuide.
 * @return boolean
 */
public boolean waxing() {
	return _waxing;
}
/**
 * This method was created by a SmartGuide.
 * @param b boolean
 */
public void waxing(boolean b) {
	_waxing = b;
}
}
