package v2;


/**
 * This class was generated by a SmartGuide.
 * 
 */
 import VideoGame.DynamicManagerI;
 import java.awt.Color;
public class Finale extends VideoGame.LevelA {
	int _counter;



/**
 * This method was created by a SmartGuide.
 * @param mcm v2.MissileCommandManager
 */
public Finale (MissileCommandManager mcm) {
	levelState(LEVEL_RUNNING);
	dynamicManagerI(mcm.dynamicManagerI());
	init();
}
/**
 * This method was created by a SmartGuide.
 * @param dm DynamicManager
 */
public void actUpon(DynamicManagerI dm) {
	if (counter() == 10 ){
	dynamicManagerI().dynamicCollection().removeAllElements();			
 	dynamicManagerI().graphics().clearRect(0,0, 500, 430);
	dynamicManagerI().graphics().setColor(Color.black);
	dynamicManagerI().graphics().drawString("Don't gimme no lip, child!", 170, 55);
	levelState(LEVEL_OVER);
	}
	else{	
	displayMessage();
	counter(counter() + 1);
}	
}
/**
 * This method was created by a SmartGuide.
 * @return int
 */
public int counter() {
	return _counter;
}
/**
 * This method was created by a SmartGuide.
 * @param i int
 */
public void counter(int i) {
	_counter = i;
}
/**
 * This method was created by a SmartGuide.
 */
public void displayMessage() {
	int x = (int)Math.round(Math.random()*400)+50;
	int y = (int)Math.round(Math.random()*300)+30;
	dynamicManagerI().graphics().setColor(Color.black);
	dynamicManagerI().graphics().drawString("Game Over", x, y);
}
/**
 * This method was created by a SmartGuide.
 */
public void init() {
	intervalBetweenActions(4);
}
}
