package v2;


import java.applet.*;
import java.awt.*;
import VideoGame.*;
/**
 * This applet was generated by a SmartGuide.
 * 
 */
public class MissileCommandApplet extends Applet {
	//**********This is the main game screen (hence the name)**************
MissileCommandScreen _missileCommandScreen;

//**********This class does the accounting for the game****************
MissileCommandManager _missileCommandManager;

//**********These are the pictures for the Bases **********************
Image baseGif;
Image cityGif;
Image deadCityGif;
Image deadBaseGif;

//**********These are the command buttons for our Applet **************
protected StartStopButton _startStopButton;
protected AboutButton _aboutButton;
protected ScoreBoardI _scoreBoardI;
//**********These numbers determine the disposition of the ************
//**********cities and bases ******************************************	
protected	int _xOffset;
	final Point POSITION_0 = new Point(10, 358);
	final int DISTANCE_AROUND_BASE = 4;
	final int DISTANCE_BETWEEN_CITIES = 48;
	final int YOFFSET_FROM_BASES_TO_CITIES = 18;
	
/**
 * Some other constants we will be using
 */
	final int GAMECLOCK_SPEED = 60;
	final int ALPHA_BASE = 122;
	final int DELTA_BASE = 120;
	final int OMEGA_BASE = 99;





/**
 * This method was created by a SmartGuide.
 * @return v2.AboutButton
 */
public AboutButton aboutButton() {
	return _aboutButton;
}
/**
 * This method was created by a SmartGuide.
 * @param a v2.AboutButton
 */
public void aboutButton(AboutButton a) {
	 _aboutButton = a;
}
/**
 * This method was created by a SmartGuide.
 */
public void addGridBoxComponent (Container cont, Component comp, GridBagLayout gbl,
	GridBagConstraints gbc, int col, int row, int wid, int hgt  ) {
	gbc.gridy = row;
	gbc.gridwidth = wid;
	gbc.gridheight = hgt;
	gbl.setConstraints(comp, gbc);
	cont.add(comp);
}
	/**
 * This method was created by a SmartGuide.
 */
public void init ( ) {
	requestFocus();
	super.init();
	/**
 * Load the images we will be using
 */
  baseGif= getImage(getDocumentBase(), "Base.gif");
  cityGif= getImage(getDocumentBase(), "City.gif");
  deadCityGif = getImage(getDocumentBase(), "DeadCity.gif");
  deadBaseGif = getImage(getDocumentBase(), "DeadBase.gif");

	missileCommandScreen(new MissileCommandScreen());
	startStopButton(new StartStopButton());
	aboutButton(new AboutButton());
	scoreBoardI(new ScoreBoard());
	layOutApplet();
	missileCommandManager(new MissileCommandManager());
	missileCommandManager().staticManagerI().imageObserver(missileCommandScreen());
	startStopButton().missileCommandManager(missileCommandManager());
	missileCommandManager().addObserver(startStopButton());
	
	startGame();
}
/**
 * This method was created by a SmartGuide.
 * @return boolean
 * @param e java.awt.Event
 */
public boolean keyDown(Event e,int Key) {
	switch(Key){
	   case ALPHA_BASE:
	   	missileCommandManager().activeBase(0);
	   	break;
	   case DELTA_BASE:
	    missileCommandManager().activeBase(1);
	   	break;
	   case OMEGA_BASE:
	   	missileCommandManager().activeBase(2);
	   	break;
	   }	
	  return super.keyDown(e, Key);


}
/**
 * This method was created by a SmartGuide.
 */
public void layOutApplet ( ) {
	setBackground(Color.white);
	
//***********************************************************
//*****This is what I want the Applet to look like: *********
//*****---------------------------------------------*********
//*****|                                           |*********
//*****|                                           |*********
//*****|                                           |*********
//*****|                                           |*********
//*****|        (main game screen)                 |*********
//*****|                                           |*********
//*****|                                           |*********
//*****|                                           |*********
//*****|                                           |*********
//*****|___________________________________________|*********
//*****| __________________ ______________________ |*********
//*****||End Game/New Game| |  About JavaCommand | |*********
//*****| ------------------ ---------------------- |*********
//*****|___________________________________________|*********

setLayout(new BorderLayout());
aboutButton().setLabel("About MissileCommander");
scoreBoardI().textField(new TextField());	
add(BorderLayout.CENTER, missileCommandScreen());
Panel buttPanel=new Panel(new GridLayout(1,3));
buttPanel.add(startStopButton());
buttPanel.add(aboutButton());
buttPanel.add(scoreBoardI().textField());
add(BorderLayout.SOUTH, buttPanel);

}
/**
 * This method was created by a SmartGuide.
 */
public void loadBase ( ) {
/**
 * determine the upper-left corner of the base
 */
		int basePositionX = POSITION_0.x + xOffset();
		int basePositionY = POSITION_0.y;
/**
 * now instantiate the base with control of the graphics
 * immediately around it
 */
		Base base = new Base(baseGif, deadBaseGif, missileCommandScreen().graphics().create(basePositionX,basePositionY, 60, 50));
		base.imageObserver(missileCommandScreen());
/**
 * increase the xOffset as appropriate
 */
		xOffset(xOffset() + DISTANCE_AROUND_BASE);
/**
 * let the base know where it is located in the gameScreen
 * and then add it to the gameManager
 */
		base.location(basePositionX, basePositionY);
		missileCommandManager().addBase(base);
/**
 * incriment and tweak the xOffset
 */
		xOffset(xOffset() + DISTANCE_AROUND_BASE + 7);
}
/**
 * This method was created by a SmartGuide.
 */
public void loadThreeCities ( ) {
	int cityNumber = 0;
	while(cityNumber < 3){
/**
 * adjust the xOffSet as appropriate
 */
		xOffset(xOffset()+DISTANCE_BETWEEN_CITIES);
/**
 * determine the position of the city in question
 */		
		int cityPositionX = POSITION_0.x+xOffset();
		int cityPositionY = POSITION_0.y+YOFFSET_FROM_BASES_TO_CITIES;
/**
 * 	tell the city where it is located, then add it to the
 *  gameManager
 */	
 		City city = new City(cityGif, deadCityGif, missileCommandScreen().getGraphics().create(cityPositionX,cityPositionY, 25, 25));
		city.imageObserver(missileCommandScreen());
		city.location(cityPositionX, cityPositionY);
		missileCommandManager().addCity(city);
		cityNumber ++; 
	}	
	xOffset(xOffset()+DISTANCE_BETWEEN_CITIES);
}
/**
 * This method was created by a SmartGuide.
 * @return v2.MissileCommandManager
 */
public MissileCommandManager missileCommandManager() {
	return _missileCommandManager;
}
/**
 * This method was created by a SmartGuide.
 * @param mm v2.MissileCommandManager
 */
public void missileCommandManager(MissileCommandManager mm) {
	_missileCommandManager = mm;
}
/**
 * This method was created by a SmartGuide.
 * @return v2.MissileCommandScreen
 */
public MissileCommandScreen missileCommandScreen() {
	return _missileCommandScreen;
}
/**
 * This method was created by a SmartGuide.
 * @param mcs v2.MissileCommandScreen
 */
public void missileCommandScreen(MissileCommandScreen mcs) {
	_missileCommandScreen = mcs;
}
/**
 * This method was created by a SmartGuide.
 * @return VideoGame.ScoreBoardI
 */
public ScoreBoardI scoreBoardI() {
	return _scoreBoardI;
}
/**
 * This method was created by a SmartGuide.
 * @param s VideoGame.ScoreBoard
 */
public void scoreBoardI(ScoreBoardI s ) {
	_scoreBoardI = s;
}
/**
 * This method was created by a SmartGuide.
 */
public void startGame() {
	missileCommandScreen().manage(missileCommandManager());
	missileCommandManager().scoreBoardI(scoreBoardI());
	xOffset(0);
	loadBase();
	loadThreeCities();
	loadBase();
	loadThreeCities();
	loadBase();
	Sky s = new Sky();
	s.missileCommandManager(missileCommandManager());
  missileCommandManager().staticManagerI().addStaticI(s);

/**
 * Now we will create the Level Manager, and begin the game in "stopped"
 * mode.
 */ 
	SmartMissileCommandLevelManager smclm = new SmartMissileCommandLevelManager();
	missileCommandManager().missileCommandLevelManager(smclm);
	smclm.missileCommandManager(missileCommandManager());
	smclm.dynamicManagerI(missileCommandManager().dynamicManagerI());
	missileCommandManager().addObserver(smclm);
	smclm.graphics(missileCommandScreen().graphics().create(90, 170, 280, 30));
	requestFocus();
	missileCommandManager().dynamicManagerI().thread(new Thread());
	missileCommandManager().endGame();}
/**
 * This method was created by a SmartGuide.
 * @return v2.StartStopButton
 */
public StartStopButton startStopButton() {
	return _startStopButton;
}
/**
 * This method was created by a SmartGuide.
 * @param s v2.StartStopButton
 */
public void startStopButton(StartStopButton s) {
	_startStopButton = s;
}
/**
 * This method was created by a SmartGuide.
 * @return int
 */
public int xOffset() {
	return _xOffset;
}
/**
 * This method was created by a SmartGuide.
 * @param i int
 */
public void xOffset(int i) {
	_xOffset = i;
}
}
