package v2;


/**
 * This class was generated by a SmartGuide.
 * 
 */
 import java.awt.Event;
public class MissileCommandScreen extends VideoGame.GameScreen {
	MissileCommandManager _missileCommandManager;





/**
 * This method was created by a SmartGuide.
 */
public MissileCommandScreen ( ) {
}
/**
 * This method was created by a SmartGuide.
 *
 * This is a helper method to manage the game screen
 * with the MissileCommandManager
 */
public void manage (MissileCommandManager mm ) {
	missileCommandManager(mm);
	dynamicManagerI(mm.dynamicManagerI());
	staticManagerI(mm.staticManagerI());
	mm.dynamicManagerI().manageableI(this);
}
/**
 * This method was created by a SmartGuide.
 * @return v2.MissileCommandManager
 */
public MissileCommandManager missileCommandManager() {
	return _missileCommandManager;
}
/**
 * This method was created by a SmartGuide.
 * @param m v2.MissileCommandManager
 */
public void missileCommandManager(MissileCommandManager m) {
	_missileCommandManager = m;
}
/**
 * This method was created by a SmartGuide.
 * @return boolean
 */
public boolean mouseDown(Event e, int x, int y) {
	if(!missileCommandManager().gameOver()){
if (e.id	== Event.MOUSE_DOWN && e.y < 345) {
		  missileCommandManager().launchMissile(e.x, e.y);
	}
	}
			return super.mouseDown(e, x, y);	
}
}
