package v2;


/**
 * This class was generated by a SmartGuide.
 * 
 */
 import VideoGame.DynamicManagerI;
 import VideoGame.LevelA;
 import java.awt.Graphics;
import java.awt.Color;
import java.util.Observer;
import java.util.Observable;
public class MissileCommandLevelManager extends VideoGame.LevelManager 
		implements Observer{
int _counter;
Graphics _graphics;
MissileCommandManager _missileCommandManager;
int _levelNumber;
String _text;


/**
 * This method was created by a SmartGuide.
 */
public MissileCommandLevelManager ( ) {
}
/**
 * This method was created by a SmartGuide.
 */
public void clearGraphics() {
		graphics().setColor(Color.white);
		graphics().fillRect(0,0, 280, 30);
;
}
/**
 * This method was created by a SmartGuide.
 */
public int counter() {
	return _counter;
}
/**
 * This method was created by a SmartGuide.
 */
public void counter(int i) {
	_counter = i;
}
/**
 * This method was created by a SmartGuide.
 * @return DynamicManagerI
 */
public DynamicManagerI  dynamicManagerI() {
	return missileCommandManager().dynamicManagerI();
}
/**
 * This method was created by a SmartGuide.
 */
public void endGame() {
	dynamicManagerI().dynamicCollection().removeAllElements();
}
/**
 * This method was created by a SmartGuide.
 * @return java.awt.Graphics
 */
public Graphics graphics() {
	return _graphics;
}
/**
 * This method was created by a SmartGuide.
 * @param g java.awt.Graphics
 */
public void graphics(Graphics g) {
	_graphics = g;
}
/**
 * This method was created by a SmartGuide.
 * @param l Level
 */
public void level(LevelA l) {
	counter(0);
	super.level(l);
}
/**
 * This method was created by a SmartGuide.
 * @return int
 */
public int levelNumber() {
	return _levelNumber;
}
/**
 * This method was created by a SmartGuide.
 */
public void levelNumber(int i) {
	_levelNumber = i;
}
/**
 * This method was created by a SmartGuide.
 * @return v2.MissileCommandManager
 */
public MissileCommandManager missileCommandManager() {
	return _missileCommandManager;
}
/**
 * This method was created by a SmartGuide.
 * @param mm v2.MissileCommandManager
 */
public void missileCommandManager(MissileCommandManager mm) {
	_missileCommandManager = mm;
}
/**
 * This method was created by a SmartGuide.
 */
public void nextLevel() {
	dynamicManagerI().graphics().clearRect(0,0, 500, 430);
	missileCommandManager().staticManagerI().drawStatics();
	ScudLevel oldLevel = (ScudLevel)level();
	ScudLevel nextLevel = new ScudLevel(oldLevel.intervalBetweenActions()+1,
	oldLevel.origNOM()+ 2, oldLevel.speedOfMissiles() * 1.4, missileCommandManager());
	nextLevel.levelNumber(oldLevel.levelNumber() + 1);
	counter(0);
	level(nextLevel);
}
/**
 * This method was created by a SmartGuide.
 */
public void restAfterLevel() { 
	if(missileCommandManager().gameOver()){
		missileCommandManager().dynamicManagerI().thread().stop();
	}//end if
	else{	
	if(missileCommandManager().dynamicManagerI().dynamicCollection().size() == 1){
		if(counter() > 0){
			String scoreString = "";
			int bonusPoints  = 0;
			counter(counter()-1);
			if(counter() < 20){
				int missiles = missileCommandManager().totalMissilesLeft();
				scoreString = (missiles +" missiles left = " + missiles + " bonus points");
				bonusPoints = missiles * 1;
			}else if(counter() < 40){
				int cities =missileCommandManager().remainingCities();
				bonusPoints = cities * 50;
				scoreString =  (" "+cities+" cities left = "+ bonusPoints +" bonus points");
			}else if(counter() <60){
				scoreString = ("       Level "+ level().levelNumber()+" completed");
				bonusPoints= 0;
				}	
			if(!(scoreString.equals(text()))){	
				clearGraphics();
				graphics().setColor(Color.black);
				graphics().drawString(scoreString,60, 25);
				text(scoreString);
				missileCommandManager().scoreBoardI().score(bonusPoints);
				}	
			}//end if		
			else{
				clearGraphics();
				missileCommandManager().ressurectBases();
				nextLevel();
			}
		}
	}	
}
/**
 * This method was created by a SmartGuide.
 */
public void restBeforeLevel() {
	if(counter() < 60){
		counter(counter()+1);
			String string = "   "+String.valueOf((60 -counter())/10);
			if (counter() >= 40)
				string = ("Ready");
			if (counter() >= 50)
				string = ("  Go");
			if (!(string.equals(text()))){					
				clearGraphics();
				graphics().setColor(Color.black);
				graphics().drawString(" " + string, 130, 25);		
			}	
	}
	else{
		clearGraphics();
		startLevel();
	}	
}
/**
 * This method was created by a SmartGuide.
 * @param sl v2.ScudLevel
 */
public void startGame() {
startGame(new ScudLevel(10, 10, .14, missileCommandManager()));
level().levelNumber(1);
}
/**
 * This method was created by a SmartGuide.
 * @param sl v2.ScudLevel
 */
public void startGame(ScudLevel sl) {
	level(sl);
}
/**
 * This method was created by a SmartGuide.
 * @return java.lang.String
 */
public String text() {
	return _text;
}
/**
 * This method was created by a SmartGuide.
 * @param s java.lang.String
 */
public void text(String s) {
	_text = s;
}
/**
 * This method was created by a SmartGuide.
 * @param ob java.util.Observer
 * @param O java.lang.Object
 */
public void update (Observable ob, Object O ) {
	if(missileCommandManager().gameOver()){
	level(new Finale(missileCommandManager()));
}
else{
	startGame(new ScudLevel(10, 10, .1, missileCommandManager()));
}		
}
}
