package v2;


/**
 * This class was generated by a SmartGuide.
 * 
 */
 import java.awt.Color;
 import java.awt.Point;
 import VideoGame.DynamicManagerI;
public class Missile extends VideoGame.Projectile {
	protected Color _color;
	protected MissileCommandManager _missileCommandManager;




/**
 * This method was created by a SmartGuide.
 */
public Missile (int x, int y, MissileCommandManager mm ) {
	startPoint(new Point(x,y));
	position(new Point(x,y));
	color(Color.blue);
	missileCommandManager(mm);
}
/**
 * This method was created by a SmartGuide.
 */
public Color color ( ) {
	return _color;
}
/**
 * This method was created by a SmartGuide.
 * @param c java.awt.Color
 */
public void color(Color c) {
	_color = c;
}
/**
 * This method was created by a SmartGuide.
 */
public void detonate ( ) {
	Explosion e = new Explosion(position().x, position().y, missileCommandManager());
  	missileCommandManager().addExplosion(e);
	graphics().setColor(Color.white);
	//This is neccesary since not all JDK's clean up after themselves...
	for(int a=-5;a< 5; a++)
		graphics().drawLine(position().x+a, position().y, startPoint().x+a, startPoint().y);
		
}
/**
 * This method was created by a SmartGuide.
 */
public void drawTail() {
	graphics().setColor(color());
	graphics().drawLine(position().x, position().y, startPoint().x, startPoint().y);
	
}
/**
 * This method was created by a SmartGuide.
 */
public void impact ( ) {
	detonate();
}
/**
 * This method was created by a SmartGuide.
 * @return v2.MissileCommandManager
 */
public MissileCommandManager missileCommandManager() {
	return _missileCommandManager;
}
/**
 * This method was created by a SmartGuide.
 * @param mm v2.MissileCommandManager
 */
public void missileCommandManager(MissileCommandManager mm) {
	dynamicManagerI(mm.dynamicManagerI());
	_missileCommandManager = mm;
}
/**
 * This method was created by a SmartGuide.
 */
public void moveTo (int x1, int y1, int x2, int y2 ) {
	graphics().setColor(color());
	graphics().drawLine(x1,y1,x2,y2);
	super.moveTo(x1,y1,x2,y2);
}
/**
 * This method was created by a SmartGuide.
 */
public void remove() {
	missileCommandManager().removeMissile(this);
	super.remove();
}
/**
 * This method was created by a SmartGuide.
 * @param p java.awt.Point
 */
public void startPoint (Point p ) {
	super.startPoint(p);
}
}
