package v2;


/**
 * This class was generated by a SmartGuide.
 * 
 */
 import java.awt.*;
 import java.util.*;
 import VideoGame.*;
 
public class MissileCommandManager extends Observable{
	protected Vector _baseCollection;
	protected Vector _explosionCollection;
	protected Vector _cityCollection;
	protected Vector _missileCollection;
	protected final int ALPHA_BASE = 122;
	protected final int DELTA_BASE = 120;
	protected final int OMEGA_BASE = 99;
	protected int _activeBase;
	protected DynamicManagerI _dynamicManagerI;
	protected StaticManagerI _staticManagerI;
	protected ScoreBoardI _scoreBoardI;
	protected MissileCommandLevelManager _missileCommandLevelManager;
	protected boolean _gameOver;
	int GAMECLOCK_SPEED = 60;



/**
 * MissileCommandManager constructor comment.
 * @param refToGameScreen v1.GameScreen
 */
public MissileCommandManager() {
	baseCollection(new Vector());
	explosionCollection(new Vector());
	cityCollection(new Vector());
	missileCollection(new Vector());
	dynamicManagerI(new DynamicManager());
	staticManagerI(new StaticManager());
	dynamicManagerI().dynamicCollection(new Vector());
	staticManagerI().staticCollection(new Vector());
}
/**
 * This method was created by a SmartGuide.
 * @return int
 */
public int activeBase ( ) {
	return _activeBase;
}
/**
 * This method was created by a SmartGuide.
 */
public void activeBase (int i) {
	_activeBase = i;
}
/**
 * This method was created by a SmartGuide.
 */
public void addBase (Base b ) {
	baseCollection().addElement(b);
  staticManagerI().addStaticI((StaticI)b);
 } 
/**
 * This method was created by a SmartGuide.
 */
public void addCity (City c ) {
	cityCollection().addElement(c);
  staticManagerI().addStaticI((StaticI)c);
}
/**
 * This method was created by a SmartGuide.
 * @param e v2.Explosion
 */
public void addExplosion (Explosion e ) {
	explosionCollection().addElement(e);
	dynamicManagerI().addDynamic((Dynamic)e);
}
/**
 * This method was created by a SmartGuide.
 */
public void addMissile (Missile m ) {
	missileCollection().addElement(m);
	dynamicManagerI().addDynamic(m);
}
/**
 * This method was created by a SmartGuide.
 * @return java.util.Vector
 */
public Vector baseCollection() {
	return _baseCollection;
}
/**
 * This method was created by a SmartGuide.
 * @param v java.util.Vector
 */
public void baseCollection(Vector v) {
	_baseCollection = v;
}
/**
 * This method was created by a SmartGuide.
 * @return java.util.Vector
 */
public Vector cityCollection() {
	return _cityCollection;
}
/**
 * This method was created by a SmartGuide.
 * @param v java.util.Vector
 */
public void cityCollection(Vector v)  {
	_cityCollection = v;
}
/**
 * This method was created by a SmartGuide.
 * @return VideoGame.DynamicManagerI
 */
public DynamicManagerI dynamicManagerI() {
	return _dynamicManagerI;
}
/**
 * This method was created by a SmartGuide.
 * @param dm VideoGame.DynamicManagerI
 */
public void dynamicManagerI(DynamicManagerI dm) {
	_dynamicManagerI = dm;
}
/**
 * This method was created by a SmartGuide.
 */
public void endGame() {
	this.setChanged();
	gameOver(true);
	missileCollection().removeAllElements();
	notifyObservers("GAME_OVER");
	activeBase(-1);
}
/**
 * This method was created by a SmartGuide.
 * @return java.util.Vector
 */
public Vector explosionCollection() {
	return _explosionCollection;
}
/**
 * This method was created by a SmartGuide.
 * @param v java.util.Vector
 */
public void explosionCollection(Vector v) {
	_explosionCollection = v;
}
/**
 * This method was created by a SmartGuide.
 * @return boolean
 */
public boolean gameOver() {
	return _gameOver;
}
/**
 * This method was created by a SmartGuide.
 * @param b boolean
 */
public void gameOver(boolean b) {
	_gameOver = b;
}
/**
 * This method was created by a SmartGuide.
 */
public BlastInfo inAnyBlastMaxArea (int x, int y ) {
	int explosionToHandle = 0;
	while (explosionToHandle < explosionCollection().size()){
	    Explosion curExplosion = (Explosion)explosionCollection().elementAt(explosionToHandle);
	    if (curExplosion.inRectangle(x,y)) {
		 BlastInfo bi = new BlastInfo();
		 bi.explosion(curExplosion);
		 bi.nullToken(false);
	    return bi;
	    }
	    explosionToHandle ++;
	}
	BlastInfo bi = new BlastInfo();
	bi.nullToken(true);
	return bi;
}
/**
 * This method was created by a SmartGuide.
 */
public boolean inAnyExplosion (int x, int y ) {
	int explosionToHandle = 0;
	while (explosionToHandle < explosionCollection().size()){
	    Explosion curExplosion = (Explosion)explosionCollection().elementAt(explosionToHandle);
	    if (curExplosion.inBlastArea(x,y)) {
	   scoreBoardI().score(20);
		return true;
	    }
	    explosionToHandle ++;
	}
	return false;
}
/**
 * This method was created by a SmartGuide.
 * @param c v2.City
 */
public void killCity(City c) {
	//first destruct the target
	c.destruct();
	//now check to determine if any cities are still alive
	if (noCityAlive()){
		endGame();
	}	
}
/**
 * This method was created by a SmartGuide.
 */
public void launchMissile (int x, int y ) {
	if (activeBase() > -1){
		if(((Base)baseCollection().elementAt(activeBase())).queryLaunchMissile()){
			Missile m = new Missile(((Base)baseCollection().elementAt(activeBase())).location().x+22,((Base)baseCollection().elementAt(activeBase())).location().y, this);
			addMissile(m);
			m.missileCommandManager(this);
			m.target(x,y,2);
		}	
	}
}
/**
 * This method was created by a SmartGuide.
 * @return java.util.Vector
 */
public Vector missileCollection() {
	return _missileCollection;
}
/**
 * This method was created by a SmartGuide.
 * @param v java.util.Vector
 */
public void missileCollection(Vector v) {
	_missileCollection = v;
}
/**
 * This method was created by a SmartGuide.
 * @return v2.MissileCommandLevelManager
 */
public MissileCommandLevelManager missileCommandLevelManager() {
	return _missileCommandLevelManager;
}
/**
 * This method was created by a SmartGuide.
 * @param mclm v2.MissileCommandLevelManager
 */
public void missileCommandLevelManager(MissileCommandLevelManager mclm) {
	_missileCommandLevelManager = mclm;
}
/**
 * This method was created by a SmartGuide.
 * @return boolean
 */
public boolean noCityAlive() {
	int a = 0;
	while (a < cityCollection().size()){
		City curCity = (City)cityCollection().elementAt(a);
		if (!(curCity.destroyed())){
			return false;
		}
		a++;
	}	
		return true;	
}
/**
 * This method was created by a SmartGuide.
 * @return boolean
 */
public boolean queryAnyLivingCities() {
	int a=0;
	while(a<cityCollection().size()){
		City curCity = (City)cityCollection().elementAt(a);
		if(curCity.destroyed() == false){
			return true;
		}
		a++;	
	}
	return false;	
}
/**
 * This method was created by a SmartGuide.
 * @return v2.City
 */
public City randomTarget() {
	int rndInt = (int)(Math.random()*9);
	City rndCity = (City)staticManagerI().staticCollection().elementAt(rndInt);
	return rndCity;
}
/**
 * This method was created by a SmartGuide.
 * @return int
 */
public int remainingCities() {
	int a = 0;
	int livingCities = 0;
	while(a < cityCollection().size()){
		City curCity = (City)cityCollection().elementAt(a);
		if (!(curCity.destroyed())){
				livingCities ++;
			}
		a++;
	}	
	return livingCities;		
}
/**
 * This method was created by a SmartGuide.
 */
public void removeExplosion (Explosion e) {
	explosionCollection().removeElement(e);
	dynamicManagerI().removeDynamic(e);
	staticManagerI().drawStatics();
}
/**
 * This method was created by a SmartGuide.
 */
public void removeMissile(Missile m) {
	missileCollection().removeElement(m);
}
/**
 * This method was created by a SmartGuide.
 */
public void ressurectACity() {
	boolean b = false;
	int a = 0;
	while (a < cityCollection().size()){
	City curCity = (City)cityCollection().elementAt(a);
	if (curCity.destroyed()==true && b == false)	{
		curCity.ressurect();	
		b=true;
	}	
	else {
		curCity.drawSelf(curCity.imageObserver());
	}
	a++;
}
}
/**
 * This method was created by a SmartGuide.
 */
public void ressurectBases() {
	int a = 0;
	while (a < 3){
		Base curBase =(Base)baseCollection().elementAt(a);
		curBase.ressurect();
		a++;
	}
	ressurectACity()	;
}
/**
 * This method was created by a SmartGuide.
 * @return VideoGame.ScoreBoard
 */
public ScoreBoardI scoreBoardI() {
	return _scoreBoardI;
}
/**
 * This method was created by a SmartGuide.
 * @param sb VideoGame.ScoreBoard
 */
public void scoreBoardI(ScoreBoardI sb) {
	_scoreBoardI = sb;
}
/**
 * This method was created by a SmartGuide.
 */
public void startGame() {
	int a = 0;
	dynamicManagerI().graphics().clearRect(0,0, 500, 430);
	while (a < cityCollection().size()){
		City curCity = (City)cityCollection().elementAt(a);
		curCity.ressurect();
		a++;
	}
	a =0;
		while (a < baseCollection().size()){
		Base curBase = (Base)baseCollection().elementAt(a);
		curBase.ressurect();
		a++;
	}

	dynamicManagerI().dynamicCollection().removeAllElements();
	explosionCollection().removeAllElements();
	scoreBoardI().points(0);
	scoreBoardI().displayScore();
	gameOver(false);
	setChanged();
	notifyObservers("GAME_STARTED");
	scoreBoardI().points(0);	
	missileCommandLevelManager().startGame();
	dynamicManagerI().addDynamic(missileCommandLevelManager());
	/**
 * Here we create a thread for the dynamicManager to
 * run in, then start it.
 */
	Thread t = new Thread((DynamicManager)dynamicManagerI());
	dynamicManagerI().thread(t);
	dynamicManagerI().delay(GAMECLOCK_SPEED);
	dynamicManagerI().thread().start();	

}
/**
 * This method was created by a SmartGuide.
 * @param mclm v2.MissileCommandLevelManager
 */
public void startGame(MissileCommandLevelManager mclm) {
	
	mclm.graphics(dynamicManagerI().graphics().create(180, 170,140,30));
	mclm.missileCommandManager(this);	
	mclm.startGame();
	dynamicManagerI().addDynamic(mclm);
}
/**
 * This method was created by a SmartGuide.
 * @return VideoGame.StaticManagerI
 */
public StaticManagerI staticManagerI() {
	return _staticManagerI;
}
/**
 * This method was created by a SmartGuide.
 * @param sm VideoGame.StaticManagerI
 */
public void staticManagerI(StaticManagerI sm) {
	_staticManagerI = sm;
}
/**
 * This method was created by a SmartGuide.
 * @return int
 */
public int totalMissilesLeft() {
	int a =0;
	int missiles = 0;
	while(a<baseCollection().size()){
		Base curBase = (Base)baseCollection().elementAt(a);
		missiles = missiles + curBase.numberOfMissiles();
		a++;
	}
	return missiles;	
}
}
