package v2;


/**
 * This class was generated by a SmartGuide.
 * 
 */
  import VideoGame.*;
public class ScudLevel extends VideoGame.LevelA {
	protected MissileCommandManager _missileCommandManager;
	protected int _numberOfMissiles;
	protected double _speedOfMissiles;
	protected int _origNOM;

/**
 * This method was created by a SmartGuide.
 * @param intervalBetweenMissiles int
 * @param numberOfMissiles int
 * @param speedOfMissiles double
 */
public ScudLevel (int intervalBetweenMissiles, int numberOfMissiles, double speedOfMissiles, MissileCommandManager mm) {
missileCommandManager(mm);
intervalBetweenActions(intervalBetweenMissiles);
numberOfMissiles(numberOfMissiles);
origNOM(numberOfMissiles);
speedOfMissiles(speedOfMissiles);
levelState(LEVEL_NOT_YET_BEGUN);
step(0);
}
/**
 * This method was created by a SmartGuide.
 */
public void actUpon (DynamicManagerI dm ) {
	if (numberOfMissiles()==0){
		levelState(LEVEL_OVER);
	}
	else{	
	deployMissile(missileCommandManager());
}	
}
/**
 * This method was created by a SmartGuide.
 * @param gm GameManager
 */
public void deployMissile (MissileCommandManager mm ) {
	numberOfMissiles(numberOfMissiles() -1);
	Scud s = new Scud((int)(Math.round(Math.random()*400)) + 50, 0,mm);
	mm.addMissile(s);
	s.target(mm.randomTarget(), speedOfMissiles());
}
/**
 * This method was created by a SmartGuide.
 */
public void initialAction (MissileCommandManager mm) {
	//fire three missiles to get started
	deployMissile(mm);
	deployMissile(mm);
	deployMissile(mm);
}
/**
 * This method was created by a SmartGuide.
 * @return v2.MissileCommandManager
 */
public MissileCommandManager missileCommandManager() {
	return _missileCommandManager;
}
/**
 * This method was created by a SmartGuide.
 * @param mm v2.MissileCommandManager
 */
public void missileCommandManager(MissileCommandManager mm) {
	_missileCommandManager = mm;
}
/**
 * This method was created by a SmartGuide.
 * @return int
 */
public int numberOfMissiles() {
	return _numberOfMissiles;
}
/**
 * This method was created by a SmartGuide.
 * @param i int
 */
public void numberOfMissiles(int i) {
	_numberOfMissiles = i;
}
/**
 * This method was created by a SmartGuide.
 * @return int
 */
public int origNOM() {
	return _origNOM;
}
/**
 * This method was created by a SmartGuide.
 * @param i int
 */
public void origNOM(int i) {
	_origNOM = i;
}
/**
 * This method was created by a SmartGuide.
 * @return int
 */
public double speedOfMissiles() {
	return _speedOfMissiles;
}
/**
 * This method was created by a SmartGuide.
 * @param i int
 */
public void speedOfMissiles (double d ) {
	_speedOfMissiles = d;
}
}
