package v2;


/**
 * This class was generated by a SmartGuide.
 * 
 */
 import java.awt.Color;
public class Scud extends Missile {
	protected City target;




/**
 * Scud constructor comment.
 * @param x int
 * @param y int
 * @param gm VideoGame.GameManager
 */
public Scud(int x, int y, MissileCommandManager mm) {
	super(x, y, mm);
	color(Color.red);
}
/**
 * This method was created by a SmartGuide.
 */
public void impact ( ) {
	missileCommandManager().killCity(target);
	super.impact();
}
/**
 * This method was created by a SmartGuide.
 */
public void move() {
super.move();	
if(queryDeath()){
detonate();
remove();
}
}
/**
 * This method was created by a SmartGuide.
 * @return boolean
 */
public boolean queryDeath() {
	return missileCommandManager().inAnyExplosion(position().x,position().y);
}
/**
 * This method was created by a SmartGuide.
 * @return v2.City
 */
public City target() {
	return target;
}
/**
 * This method was created by a SmartGuide.
 * @param c v2.City
 * @param speed int
 */
public void target (City c, double speed ) {
	target = c;
	super.target(c.location().x + 20, c.location().y + 30, speed);
}
}
