package v2;


/**
 * This class was generated by a SmartGuide.
 * 
 */
 import java.awt.image.ImageObserver;
public class Sky extends VideoGame.Stationary {
	MissileCommandManager _missileCommandManager;
	

/**
 * This method was created by a SmartGuide.
 */
public void drawSelf(ImageObserver ia) {
	drawTails();
}
/**
 * This method was created by a SmartGuide.
 */
public void drawTails() {
	int a = 0;
	while(a< missileCommandManager().missileCollection().size()){
		Missile curMissile = (Missile)missileCommandManager().missileCollection().elementAt(a);
		curMissile.drawTail();
		a++;
	}	
}
/**
 * This method was created by a SmartGuide.
 * @return v2.MissileCommandManager
 */
public MissileCommandManager missileCommandManager() {
	return _missileCommandManager;
}
/**
 * This method was created by a SmartGuide.
 * @param mcm v2.MissileCommandManager
 */
public void missileCommandManager(MissileCommandManager mcm) {
	_missileCommandManager = mcm;
}
}
