package v2;


/**
 * This class was generated by a SmartGuide.
 * 
 */
import java.awt.Graphics;
import java.awt.Color;
public class SmartMissile extends Scud {
		double _speed;

/**
 * SmartMissile constructor comment.
 * @param x int
 * @param y int
 * @param mm v2.MissileCommandManager
 */
public SmartMissile(int x, int y, MissileCommandManager mm) {
	super(x, y, mm);
}
/**
 * This method was created by a SmartGuide.
 */
public void clearCurrentArea() {
	graphics().setColor(Color.white);
	graphics().fillOval(position().x -2, position().y -2, 4, 4);
}
/**
 * This method was created by a SmartGuide.
 * @param g Graphics
 */
public void drawSelf() {
	graphics().setColor(Color.red);
	graphics().fillOval(position().x -2, position().y -2, 4, 4);
}
/**
 * This method was created by a SmartGuide.
 */
public void drawTail() {
	return;
}
/**
 * This method was created by a SmartGuide.
 */
public void evade(Explosion e) {

/**
* Determine how far the explosion is from
* the missile, and useing this determine what
* number of moves away the epicenter is.
*/
double distanceFromExplosion = Math.sqrt(Math.abs((e.position().x-position().x)^2 + Math.abs(e.position().y-position().y)^2));
double turnsFromExplosion = distanceFromExplosion/speed();

/**
* Determine the x and y offsets from the
* explosion center
*/

int xOffSet = e.position().x - position().x;
int yOffSet = e.position().y - position().y;

/**
 * using this information we can now determine the 
 * missile's new location
 */
int dodgeX = (int)Math.round(xOffSet/turnsFromExplosion);
int dodgeY = (int)Math.round(yOffSet/turnsFromExplosion);

moveTo(position().x, position().y, position().x - dodgeX, position().y - dodgeY);
/**
 * Don't forget to check for death and re-target
 */
 if (queryDeath()){
 	detonate();
 	remove();
 }
 else{	
	target(target(), speed());
	}	
}
/**
 * This method was created by a SmartGuide.
 * @return v2.BlastInfo
 */
public BlastInfo lookAhead() {
	BlastInfo bi;
	bi = missileCommandManager().inAnyBlastMaxArea(position().x+ xPerMove() , position().y+ yPerMove());
	return bi;
}
/**
 * This method was created by a SmartGuide.
 */
public void move() {
	BlastInfo bi = lookAhead();
	if (!bi.nullToken()){
		evade(bi.explosion());
	}
	else{
		super.move();
	}	
}
/**
 * This method was created by a SmartGuide.
 * @param x1 int
 * @param y1 int
 * @param x2 int
 * @param y2 int
 */
public void moveTo(int x1, int y1, int x2, int y2) {
	clearCurrentArea();
	position(x2, y2);
	drawSelf();
}
/**
 * This method was created by a SmartGuide.
 * @return double
 */
public double speed() {
	return _speed;
}
/**
 * This method was created by a SmartGuide.
 * @param d double
 */
public void speed (double d ) {
	_speed =d;
}
/**
 * This method was created by a SmartGuide.
 * @param x int
 * @param y int
 * @param speed int
 */
public void target(City c, double speed) {
	speed(speed);
	super.target(c,speed);
}
}
