package v2;


/**
 * This class was generated by a SmartGuide.
 * 
 */
public class SmartMissileCommandLevelManager extends MissileCommandLevelManager {

/**
 * SmartMissileCommandLevelManager constructor comment.
 */
public SmartMissileCommandLevelManager() {
	super();
}
/**
 * This method was created by a SmartGuide.
 */
public void nextLevel() {
	dynamicManagerI().graphics().clearRect(0,0, 500, 430);
	missileCommandManager().staticManagerI().drawStatics();
	ScudLevel oldLevel = (ScudLevel)level();
	/**
	* on odd levels, increase the interval between missiles
	*/
	int incriment;
	incriment = 0;
	if((level().levelNumber()/2)*2==level().levelNumber()){
		incriment ++;
	}	
	SmartMissileLevel nextLevel = new SmartMissileLevel(oldLevel.intervalBetweenActions()+incriment,
	oldLevel.origNOM()+ 2, oldLevel.speedOfMissiles() * 1.1, missileCommandManager());
	nextLevel.levelNumber(oldLevel.levelNumber() + 1);
	counter(0);
	level(nextLevel);
}
/**
 * This method was created by a SmartGuide.
 */
public void startGame() {
startGame(new SmartMissileLevel(10, 10, .14, missileCommandManager()));
level().levelNumber(1);
}
}
