package v2;


/**
 * This class was generated by a SmartGuide.
 * 
 */
public class SmartMissileLevel extends ScudLevel {
	int _numberOfSmartMissiles;

/**
 * SmartMissileLevel constructor comment.
 * @param intervalBetweenMissiles int
 * @param numberOfMissiles int
 * @param speedOfMissiles double
 * @param mm v2.MissileCommandManager
 */
public SmartMissileLevel(int intervalBetweenMissiles, int numberOfMissiles, double speedOfMissiles, MissileCommandManager mm) {
	super(intervalBetweenMissiles, numberOfMissiles, speedOfMissiles, mm);
	numberOfSmartMissiles(Math.round((numberOfMissiles - 10)/3));
}
/**
 * This method was created by a SmartGuide.
 * @param mm v2.MissileCommandManager
 */
public void deployMissile(MissileCommandManager mm) {
	int rint = (int)Math.round(Math.random()* (numberOfMissiles()-1)+1);
	if (rint <= numberOfSmartMissiles()){
		deploySmartMissile();
	}
	else{
		super.deployMissile(mm);
	}		
}
/**
 * This method was created by a SmartGuide.
 */
public void deploySmartMissile() {
	numberOfMissiles(numberOfMissiles() -1);
	numberOfSmartMissiles(numberOfSmartMissiles() -1);
	SmartMissile sm = new SmartMissile((int)(Math.round(Math.random()*400)) + 50, 0,missileCommandManager());
	missileCommandManager().addMissile(sm);
	sm.target(livingTarget(), speedOfMissiles());
}
/**
 * This method was created by a SmartGuide.
 * @return v2.City
 */
public City livingTarget() {
	City target= missileCommandManager().randomTarget();
	while(target.destroyed()){
		target = missileCommandManager().randomTarget();
	}	
	return target;
}
/**
 * This method was created by a SmartGuide.
 * @return int
 */
public int numberOfSmartMissiles() {
	return _numberOfSmartMissiles;
}
/**
 * This method was created by a SmartGuide.
 * @param i int
 */
public void numberOfSmartMissiles(int i) {
	_numberOfSmartMissiles = i;
}
}
