package v2;


/**
 * This class was generated by a SmartGuide.
 * 
 */
 import java.awt.Event;
 import VideoGame.DynamicManagerI;
 import java.util.*;
public class StartStopButton 
	extends java.awt.Button implements Observer{
MissileCommandManager _missileCommandManager;
public final int START = 0;
public final int STOP = 1;
protected int _buttonState;



/**
 * StartStopButton constructor comment.
 */
public StartStopButton() {
	super();
	buttonState(STOP);
}
/**
 * StartStopButton constructor comment.
 * @param label java.lang.String
 */
public StartStopButton(String label) {
	super(label);
}
/**
 * This method was created by a SmartGuide.
 * @return int
 */
public int buttonState() {
	return _buttonState;
}
/**
 * This method was created by a SmartGuide.
 * @param i int
 */
public void buttonState(int i) {
	_buttonState = i;
	if (i == 0){
		setLabel("Start Game");
	}
	else{
		setLabel("End Game");
	}		
}
/**
 * This method was created by a SmartGuide.
 * @return boolean
 * @param e java.awt.Event
 */
public boolean handleEvent(Event e) {
	if (e.id==1001){
		switch (buttonState()){
			case START:			
			missileCommandManager().startGame();
			break;
			case STOP:
			missileCommandManager().endGame();
			break;
		}	
}
	return super.handleEvent(e);
	
}
/**
 * This method was created by a SmartGuide.
 * @return v2.MissileCommandManager
 */
public MissileCommandManager missileCommandManager() {
	return _missileCommandManager;
}
/**
 * This method was created by a SmartGuide.
 * @param mm v2.MissileCommandManager
 */
public void missileCommandManager(MissileCommandManager mm) {
	_missileCommandManager = mm;
}
/**
 * This method was created by a SmartGuide.
 * @param o java.util.Observable
 * @param o2 java.lang.Object
 */
public void update(Observable ob, Object oj) {
	if (oj.equals("GAME_OVER")){
		buttonState(START);
	}
	else if (oj.equals("GAME_STARTED")){
		buttonState(STOP);
	}		
}
}
