package VideoGame;


/**
 * This type was generated by a SmartGuide.
 * @author Daniel Drasin
 */
public interface ActorI extends VideoGame.Dynamic {






/**
 * This method was created by a SmartGuide.
 * @param dm VideoGame.DynamicManagerI
 */
public void actUpon(DynamicManagerI dm);
/**
 * This method was created by a SmartGuide.
 * @return VideoGame.DynamicManagerI
 */
public DynamicManagerI dynamicManagerI();
/**
 * This method was created by a SmartGuide.
 * @param dm VideoGame.DynamicManagerI
 */
public void dynamicManagerI (DynamicManagerI dm );
}
