package VideoGame;


/**
 * This type was generated by a SmartGuide.
 * @author Daniel Drasin
 */
public abstract class ActorA implements VideoGame.ActorI {
		DynamicManagerI _dynamicManagerI;






/**
 * actUpon method comment.
 */
public void actUpon(DynamicManagerI dm) {
}
/**
 * dynamicManagerI method comment.
 */
public DynamicManagerI dynamicManagerI() {
	return _dynamicManagerI;
}
/**
 * dynamicManagerI method comment.
 */
public void dynamicManagerI(DynamicManagerI dm) {
		_dynamicManagerI= dm;
}
/**
 * move method comment.
 */
public void move() {
		actUpon(dynamicManagerI());
}
}
