package VideoGame;


/**
 * This class was generated by a SmartGuide.
 * 
 */
 import java.awt.*;
public class BenLogo extends Frame implements Runnable {



/**
 * This method was created by a SmartGuide.
 */
public void addItemsToWindow() {
	FlowLayout fl = new FlowLayout();
	Label logo = new Label("Written by Benjamin Drasin, Copyright 1997");
	Label slogan = new Label(" 'Don't gimme no lip, child!' ");
	add(logo);
	add(slogan);
	fl.layoutContainer(this);
}
/**
 * This method was created by a SmartGuide.
 * @return boolean
 * @param e java.awt.Event
 */
public boolean handleEvent(Event e) {
	if (e.id == 201){
		dispose();
	}		
	return super.handleEvent(e);
}
	/**
 * This method was created by a SmartGuide.
 */
public void makeWindow() {
resize(350, 140);
setResizable(false);
setVisible(true);
}
/**
 * This method was created by a SmartGuide.
 */
public void run() {
	makeWindow();
	addItemsToWindow();
}
}
