package VideoGame;


/**
 * This class was generated by a SmartGuide.
 * 
 */
 import java.util.Vector;
 import java.awt.Graphics;
 import java.awt.Color;
public class DynamicManager implements VideoGame.DynamicManagerI, Runnable {
	protected Thread _thread;
	protected volatile boolean _paused = false;
	protected int _gameState;
	protected int _delay;
	protected Vector _dynamicCollection;
	protected long _markTime;
	final int GAME_RUNNING = 0;
	final int GAME_PAUSED = 1;
	final int GAME_IDLE = 2;
	protected ManageableI _manageableI;
	protected ScoreBoardI _scoreBoardI;






/**
 * addDynamic method comment.
 */
public void addDynamic(Dynamic d) {
	dynamicCollection().addElement(d);
}
/**
 * This method was created by a SmartGuide.
 */
public void clearRect() {
	graphics().setColor(Color.white);
	graphics().fillRect(0,0,500, 320);
}
/**
 * This method was created by a SmartGuide.
 */
public void clearRect(int x, int y, int hgt, int wid) {
	graphics().setColor(Color.white);
	graphics().fillRect(x,y,hgt,wid);
}
/**
 * This method was created by a SmartGuide.
 * @return int
 */
public int delay() {
	return _delay;
}
/**
 * This method was created by a SmartGuide.
 * @param d int
 */
public void delay(int d) {
	_delay = d;
}
/**
 * dynamicCollection method comment.
 */
public java.util.Vector dynamicCollection() {
	return _dynamicCollection;
}
/**
 * dynamicCollection method comment.
 */
public void dynamicCollection(java.util.Vector v) {
	_dynamicCollection = v;
}
/**
 * This method was created by a SmartGuide.
 * @return int
 */
public int gameState() {
	return _gameState;
}
/**
 * This method was created by a SmartGuide.
 * @param i int
 */
public void gameState(int i) {
	_gameState = i;
}
/**
 * This method was created by a SmartGuide.
 * @return java.awt.Graphics
 */
public Graphics graphics() {
	return manageableI().graphics();
}
/**
 * This method was created by a SmartGuide.
 * @param g java.awt.Graphics
 */
public void graphics(Graphics g) {
	manageableI().graphics(g);
}
/**
 * This method was created by a SmartGuide.
 */
public void loopAndMove() {
				while(true){	// infinite loop
								 synchronized(this){
								 	while(_paused){
								 		try{ wait(); } catch(InterruptedException e){}
								 	}
								 }
								 markTime(System.currentTimeMillis());
								 moveAll();
								 int sleepDur = (int)Math.round((markTime()+delay())-System.currentTimeMillis());
								 if (sleepDur < 0){
								 	tooSlow();
								 	sleepDur = 0;
								 }
								 try{
								 		thread().sleep(sleepDur);


								 		}// end try
								 catch(InterruptedException e){}
				}//end while

}
/**
 * This method was created by a SmartGuide.
 * @return VideoGame.ManageableI
 */
public ManageableI manageableI() {
	return _manageableI;
}
/**
 * This method was created by a SmartGuide.
 * @param m VideoGame.ManageableI
 */
public void manageableI(ManageableI m) {
	_manageableI = m;
}
/**
 * This method was created by a SmartGuide.
 * @return int
 */
public long markTime() {
	return _markTime;
}
/**
 * This method was created by a SmartGuide.
 * @param i int
 */
public void markTime(long l) {
	_markTime = l;
}
/**
 * This method was created by a SmartGuide.
 */
public void moveAll ( ) {
	int dyToHandle = 0;
	while( dyToHandle < dynamicCollection().size()){
			Dynamic curDy = (Dynamic)dynamicCollection().elementAt(dyToHandle);
			curDy.move();
			dyToHandle ++;
	}	//end while

}
/**
 * This method was created by a SmartGuide.
 */
public synchronized void pauseGame() {
	_paused = true;
}
/**
 * removeDynamic method comment.
 */
public void removeDynamic(Dynamic d) {
	dynamicCollection().removeElement(d);
}
/**
 * This method was created by a SmartGuide.
 */
public synchronized void resumeGame() {
	_paused = false;
	notifyAll();
}
/**
 * This method was created by a SmartGuide.
 */
public void run() {
	gameState(GAME_RUNNING);
	loopAndMove();
}
/**
 * thread method comment.
 */
public Thread thread() {
	return _thread;
}
/**
 * thread method comment.
 */
public void thread(Thread t) {
	_thread = t;
}
/**
 * This method was created by a SmartGuide.
 * This method fires when a move is being made
 * later than it ought to have.  In other words,
 * the client machine is too slow.
 */
public void tooSlow() {
}
}
