package VideoGame;


/**
 * This interface was generated by a SmartGuide.
 * 
 */
 import java.util.Vector;
 import java.awt.Graphics;
public interface DynamicManagerI {







/**
 * This method was created by a SmartGuide.
 * @param d VideoGame.Dynamic
 */
public void addDynamic (Dynamic d );
/**
 * This method was created by a SmartGuide.
 * @param x int
 * @param y int
 * @param hgt int
 * @param wid int
 */
public void clearRect(int x, int y, int hgt, int wid);
/**
 * This method was created by a SmartGuide.
 * @return int
 */
public int delay();
/**
 * This method was created by a SmartGuide.
 * @param d int
 */
public void delay(int d);
/**
 * This method was created by a SmartGuide.
 * @return Vector
 */
public Vector dynamicCollection ( );
/**
 * This method was created by a SmartGuide.
 * @param v java.util.Vector
 */
public void dynamicCollection (Vector v );
/**
 * This method was created by a SmartGuide.
 * @return Graphics
 */
public Graphics graphics();
/**
 * This method was created by a SmartGuide.
 * @param g Graphics
 */
public void graphics(Graphics g);
/**
 * This method was created by a SmartGuide.
 * @return VideoGame.ManageableI
 */
public ManageableI manageableI();
/**
 * This method was created by a SmartGuide.
 * @param m VideoGame.ManageableI
 */
public void manageableI(ManageableI m);
/**
 * This method was created by a SmartGuide.
 * @return int
 */
public long markTime();
/**
 * This method was created by a SmartGuide.
 * @param i int
 */
public void markTime(long l);
/**
 * This method was created by a SmartGuide.
 */
public void moveAll ( );
/**
 * This method was created by a SmartGuide.
 */
public void pauseGame();
/**
 * This method was created by a SmartGuide.
 * @param d VideoGame.Dynamic
 */
public void removeDynamic (Dynamic d );
/**
 * This method was created by a SmartGuide.
 */
public void resumeGame();
/**
 * This method was created by a SmartGuide.
 */
public void run();
/**
 * This method was created by a SmartGuide.
 * @return java.lang.Thread
 */
public Thread thread();
/**
 * This method was created by a SmartGuide.
 * @param t java.lang.Thread
 */
public void thread (Thread t );
/**
 * This method was created by a SmartGuide.
 */
public void tooSlow();
}
