package VideoGame;


/**
 * This class was generated by a SmartGuide.
 * 
 */
 import java.awt.Graphics;
 import java.awt.Event;
public class GameScreen extends java.awt.Canvas implements VideoGame.ManageableI {
	protected DynamicManagerI  _dynamicManagerI;
	protected StaticManagerI _staticManagerI;







/**
 * GameScreen constructor comment.
 */
public GameScreen() {
	super();
}
/**
 * This method was created by a SmartGuide.
 * @return VideoGame.DynamicManagerI
 */
public DynamicManagerI dynamicManagerI() {
	return _dynamicManagerI;
}
/**
 * This method was created by a SmartGuide.
 * @param dm VideoGame.DynamicManagerI
 */
public void dynamicManagerI(DynamicManagerI dm) {
	_dynamicManagerI= dm;
}
/**
 * graphics method comment.
 */
public java.awt.Graphics graphics() {
	return getGraphics();
}
/**
 * graphics method comment.
 */
public void graphics(java.awt.Graphics g) {
}
/**
 * imageObserver method comment.
 */
public java.awt.image.ImageObserver imageObserver() {
	return this;
}
/**
 * imageObserver method comment.
 */
public void imageObserver(java.awt.image.ImageObserver io) {
}
/**
 * This method was created by a SmartGuide.
 * @return boolean
 * @param evt java.awt.Event
 * @param x int
 * @param y int
 */
public boolean mouseEnter(Event evt, int x, int y) {
	dynamicManagerI().resumeGame();
	return super.mouseEnter(evt,x,y);
}
/**
 * This method was created by a SmartGuide.
 * @return boolean
 * @param evt java.awt.Event
 * @param x int
 * @param y int
 */
public  boolean mouseExit(Event evt, int x, int y)  {
	dynamicManagerI().pauseGame();
	return super.mouseExit(evt, x, y);
}
/**
 * This method was created by a SmartGuide.
 */
public void paint(Graphics g) {
		staticManagerI().drawStatics();
}
/**
 * This method was created by a SmartGuide.
 * @return VideoGame.StaticManagerI
 */
public StaticManagerI staticManagerI() {
	return _staticManagerI;
}
/**
 * This method was created by a SmartGuide.
 * @param sm VideoGame.StaticManagerI
 */
public void staticManagerI(StaticManagerI sm) {
	_staticManagerI= sm	;
}
}
