package VideoGame;


/**
 * This type was generated by a SmartGuide.
 * @author Daniel Drasin
 */
public interface LevelI extends VideoGame.ActorI {




/**
 * This method was created by a SmartGuide.
 */
public int intervalBetweenActions ( );
/**
 * This method was created by a SmartGuide.
 */
public void intervalBetweenActions (int i );
/**
 * This method was created by a SmartGuide.
 * @return int
 */
public int levelNumber();
/**
 * This method was created by a SmartGuide.
 */
public void levelNumber(int i);
/**
 * This method was created by a SmartGuide.
 * @return int
 */
public int levelState();
/**
 * This method was created by a SmartGuide.
 * @param i int
 */
public void levelState (int i );
/**
 * This method was created by a SmartGuide.
 * @return int
 */
public int step();
/**
 * This method was created by a SmartGuide.
 * @param i int
 */
public void step(int i);
}
