package VideoGame;


/**
 * This class was generated by a SmartGuide.
 * 
 */
public class LevelManager extends ActorA {
	protected LevelI _levelI;
	protected int _delayBetweenLevels = 10;
	protected int _elapsedTime;



/**
 * This method was created by a SmartGuide.
 * @param gm VidioGame.GameManager
 */
public void actUpon(DynamicManagerI dm) {
	switch (level().levelState()){
		case LevelA.LEVEL_NOT_YET_BEGUN:
			restBeforeLevel();
			break;
		case LevelA.LEVEL_RUNNING:
			level().move();
			break;
		case LevelA.LEVEL_OVER:
			restAfterLevel();
			break;
		}//end switch	
}
/**
 * This method was created by a SmartGuide.
 * @return VidioGame.Level
 */
public LevelI level() {
	return _levelI;
}
/**
 * This method was created by a SmartGuide.
 * @param l VidioGame.Level
 */
public void level(LevelI l) {
	_levelI = l;
}
/**
 * This method was created by a SmartGuide.
 */
public void restAfterLevel() {
	return;
}
/**
 * This method was created by a SmartGuide.
 */
public void restBeforeLevel() {
	return;
}
/**
 * This method was created by a SmartGuide.
 */
public void startLevel() {
	level().levelState(LevelA.LEVEL_RUNNING);
}
}
