package VideoGame;


/**
 * This type was generated by a SmartGuide.
 * @author Daniel Drasin
 */
public class LevelA implements VideoGame.LevelI {
	protected DynamicManagerI _dynamicManagerI;
	protected int _step;
	protected int _intervalBetweenActions;
	public final static int LEVEL_NOT_YET_BEGUN = 0;
	public final static int LEVEL_RUNNING = 1;
	public final static int LEVEL_OVER = 2;
	protected int _levelState;
	protected int _levelNumber;





/**
 * actUpon method comment.
 */
public void actUpon(DynamicManagerI dm) {
}
/**
 * dynamicManagerI method comment.
 */
public DynamicManagerI dynamicManagerI() {
	return _dynamicManagerI;
}
/**
 * dynamicManagerI method comment.
 */
public void dynamicManagerI(DynamicManagerI dm) {
	_dynamicManagerI = dm;
}
/**
 * intervalBetweenActions method comment.
 */
public int intervalBetweenActions() {
	return _intervalBetweenActions;
}
/**
 * intervalBetweenActions method comment.
 */
public void intervalBetweenActions(int i) {
	_intervalBetweenActions = i;
}
/**
 * This method was created by a SmartGuide.
 * @return int
 */
public int levelNumber() {
	return _levelNumber;
}
/**
 * This method was created by a SmartGuide.
 * @param i int
 */
public void levelNumber (int i ) {
	_levelNumber = i;
}
/**
 * levelState method comment.
 */
public int levelState() {
	return _levelState;
}
/**
 * levelState method comment.
 */
public void levelState(int i) {
	_levelState = i;
}
/**
 * move method comment.
 */
public void move() {
		if((step() >= intervalBetweenActions())){
			step(0);
			actUpon(dynamicManagerI());
			}//end if	
		else{
			step(step()+1);
		}		
}
/**
 * step method comment.
 */
public int step() {
	return _step;
}
/**
 * step method comment.
 */
public void step(int i) {
	_step = i;
}
}
