package VideoGame;


/**
 * This class was generated by a SmartGuide.
 * 
 */
public class Level {
	protected int _step;
	protected int _intervalBetweenActions;
	final int LEVEL_NOT_YET_BEGUN = 0;
	final int LEVEL_RUNNING = 1;
	final int LEVEL_OVER = 2;
	protected int _levelState;




/**
 * This method was created by a SmartGuide.
 * @param gm VidioGame.GameManager
 */
/**
 * Override this method in subclass to get desired behavior
 */
public void actUpon (DynamicManagerI dm) {
	return;
}
/**
 * This method was created by a SmartGuide.
 */
public void beginLevel ( ) {
	levelState(LEVEL_RUNNING);
}
/**
 * This method was created by a SmartGuide.
 */
public void endLevel() {
	levelState(LEVEL_OVER);
}
/**
 * This method was created by a SmartGuide.
 */
public void finalAction() {
	return;
}
/**
 * This method was created by a SmartGuide.
 */
public void finalAction(DynamicManagerI dm) {
	endLevel();
}
/**
 * This method was created by a SmartGuide.
 */
/**
 *  Note that this does not automatically
 *  start the level- the beginLevel method does that.
 */
public void initialAction(DynamicManagerI dm) {
	levelState(LEVEL_RUNNING);
}
/**
 * This method was created by a SmartGuide.
 * @return int
 */
public int intervalBetweenActions() {
	return _intervalBetweenActions;
}
/**
 * This method was created by a SmartGuide.
 * @param i int
 */
public void intervalBetweenActions(int i) {
	_intervalBetweenActions=i;
}
/**
 * This method was created by a SmartGuide.
 * @return int
 */
public int levelState() {
	return _levelState;
}
/**
 * This method was created by a SmartGuide.
 * @param i int
 */
public void levelState(int i) {
	_levelState = i;
}
/**
 * This method was created by a SmartGuide.
 */
public void nextAction (DynamicManagerI dm) {
	if(queryAction()){
		switch (levelState()){
			case LEVEL_NOT_YET_BEGUN:
				initialAction(dm);
				break;
			case LEVEL_RUNNING:
				actUpon(dm);
				break;
			case LEVEL_OVER:
				finalAction(dm);
				break;
		}//end switch	
	}	
}
/**
 * This method was created by a SmartGuide.
 */
public boolean queryAction ( ) {
	if (step() < intervalBetweenActions()){
		step(step() + 1);
		return false;
	}
	else {
		step(0);
		return true;
	}		
}
/**
 * This method was created by a SmartGuide.
 * @return int
 */
public int step() {
	return _step;
}
/**
 * This method was created by a SmartGuide.
 * @param i int
 */
public void step(int i) {
	_step = i;
}
}
