package VideoGame;


/**
 * This interface was generated by a SmartGuide.
 * 
 */
 import java.awt.image.ImageObserver;
 import java.awt.Graphics;
public interface ManageableI{







/**
 * This method was created by a SmartGuide.
 * @return java.awt.Graphics
 */
public Graphics graphics();
/**
 * This method was created by a SmartGuide.
 * @param g java.awt.Graphics
 */
public void graphics(Graphics g);
/**
 * This method was created by a SmartGuide.
 * @return java.awt.image.ImageObserver
 */
public ImageObserver imageObserver ( );
/**
 * This method was created by a SmartGuide.
 * @param io java.awt.image.ImageObserver
 */
public void imageObserver (ImageObserver io );
}
