package VideoGame;


import java.awt.*;
/**
 * This class was generated by a SmartGuide.
 * 
 */
public abstract class Projectile extends Transient {
	private Point _startPoint;
	private int _xPerMove;
	private int _yPerMove;
	private DynamicManagerI _dynamicManagerI;







/**
 * This method was created by a SmartGuide.
 */
/**
 * override this method to insert impact behavior
 */
public void impact ( ) {

	return;
}
/**
 * This method was created by a SmartGuide.
 */
public void move ( ) {
	moveTo(position().x, position().y, position().x+xPerMove(), position().y+yPerMove());
	super.move();
}
/**
 * This method was created by a SmartGuide.
 */
public void moveTo (int x1, int y1,int x2,int y2){
	position(x2, y2);
}
/**
 * This method was created by a SmartGuide.
 */
public void remove() {
	if(duration() ==0){// must have hit the target
		impact();
	}
	super.remove();	
}
/**
 * This method was created by a SmartGuide.
 * @return java.awt.Point
 */
public Point startPoint() {
	return _startPoint;
}
/**
 * This method was created by a SmartGuide.
 * @param x int
 * @param y int
 */
public void startPoint(int x, int y) {
	_startPoint = new Point(x,y);
}
/**
 * This method was created by a SmartGuide.
 * @param p java.awt.Point
 */
public void startPoint(Point p) {
	_startPoint = p;
}
/**
 * This method was created by a SmartGuide.
 * @param x int
 * @param y int
 * @param speed double
 */
public void target(int x, int y, double speed ) {
	/**
	 * No heavy wizardry here, just distance formula calculations.
	 */
	double distanceToTarget = Math.sqrt(Math.abs((x-position().x)^2 + Math.abs(y-position().y)^2));
	double dDuration = distanceToTarget/speed;
	duration((int)Math.round(dDuration));
	int xOffset = x-position().x;
	int yOffset = y-position().y;
	xPerMove((int)Math.round((x-position().x)/dDuration));
	yPerMove((int)Math.round((y-position().y)/dDuration));
}
/**
 * This method was created by a SmartGuide.
 * @return int
 */
public int xPerMove() {
	return _xPerMove;
}
/**
 * This method was created by a SmartGuide.
 * @param i int
 */
public void xPerMove(int i) {
	_xPerMove = i;
}
/**
 * This method was created by a SmartGuide.
 * @return int
 */
public int yPerMove() {
	return _yPerMove;
}
/**
 * This method was created by a SmartGuide.
 * @param i int
 */
public void yPerMove(int i) {
	_yPerMove = i;
}
}
