package VideoGame;


/**
 * This class was generated by a SmartGuide.
 * 
 */
 import java.awt.TextField;
public class ScoreBoard implements VideoGame.ScoreBoardI {
	protected int _points;
	protected TextField _textField;



/**
 * This method was created by a SmartGuide.
 */
public void displayScore() {
	textField().setText("Score: "+points());
}
/**
 * points method comment.
 */
public int points() {
	return _points;
}
/**
 * points method comment.
 */
public void points(int points) {
	_points = points;
}
/**
 * score method comment.
 */
public void score(int i) {
	points(points()+i);
	displayScore();
}
/**
 * This method was created by a SmartGuide.
 * @return java.awt.TextField
 */
public TextField textField() {
	return _textField;
}
/**
 * This method was created by a SmartGuide.
 * @param tf java.awt.TextField
 */
public void textField(TextField tf) {
	tf.setEditable(false);
	_textField = tf;
}
}
