package VideoGame;


/**
 * This interface was generated by a SmartGuide.
 * 
 */
 import java.awt.TextField;
public interface ScoreBoardI {



/**
 * This method was created by a SmartGuide.
 */
public void displayScore();
/**
 * This method was created by a SmartGuide.
 * @return int
 */
public int points();
/**
 * This method was created by a SmartGuide.
 * @param points int
 */
public void points(int points);
/**
 * This method was created by a SmartGuide.
 * @param i int
 */
public void score(int i);
/**
 * This method was created by a SmartGuide.
 * @return java.awt.TextField
 */
public TextField textField();
/**
 * This method was created by a SmartGuide.
 * @param tf TextField
 */
public void textField(TextField tf);
}
