package VideoGame;


/**
 * This interface was generated by a SmartGuide.
 * 
 */
 import java.util.Vector;
 import java.awt.image.ImageObserver;
public interface StaticManagerI {







/**
 * This method was created by a SmartGuide.
 */
public void addStaticI (StaticI s );
/**
 * This method was created by a SmartGuide.
 */
public void drawStatics ( );
/**
 * This method was created by a SmartGuide.
 * @return java.awt.image.ImageObserver
 */
public ImageObserver imageObserver();
/**
 * This method was created by a SmartGuide.
 * @param ia ImageObserver
 */
public void imageObserver (ImageObserver ia);
/**
 * This method was created by a SmartGuide.
 */
public void removeStaticI (StaticI s );
/**
 * This method was created by a SmartGuide.
 * @return Vector
 */
public Vector staticCollection();
/**
 * This method was created by a SmartGuide.
 * @param v java.util.Vector
 */
public void staticCollection(Vector v);
}
