package VideoGame;


/**
 * This class was generated by a SmartGuide.
 * 
 */
 import java.awt.*;
 import java.awt.image.ImageObserver;
public abstract class Stationary implements StaticI{
	protected int _positionX;
	protected int _positionY;
	protected Graphics _graphics;
	protected Image _image;
	protected ImageObserver _imageObserver;





/**
 * This method was created by a SmartGuide.
 * @param ia java.awt.image.ImageObserver
 */
public void drawSelf (ImageObserver ia) {
	  boolean b = graphics().drawImage(image(), 0, 0, ia);
}
/**
 * This method was created by a SmartGuide.
 * @return java.awt.Graphics
 */
public Graphics graphics() {
	return _graphics;
}
/**
 * This method was created by a SmartGuide.
 * @param g java.awt.Graphics
 */
public void graphics(Graphics g) {
	_graphics = g;
}
/**
 * This method was created by a SmartGuide.
 * @return java.awt.Image
 */
public Image image() {
	return _image;
}
/**
 * This method was created by a SmartGuide.
 * @param i java.awt.Image
 */
public void image(Image i) {
	_image = i;
}
/**
 * This method was created by a SmartGuide.
 * @return java.awt.image.ImageObserver
 */
public ImageObserver imageObserver() {
	return _imageObserver;
}
/**
 * This method was created by a SmartGuide.
 * @param ia java.awt.image.ImageObserver
 */
public void imageObserver(ImageObserver ia) {
	_imageObserver = ia;
}
/**
 * This method was created by a SmartGuide.
 * @return Point
 */
public Point location ( ) {
	return new Point(_positionX, _positionY);
}
/**
 * This method was created by a SmartGuide.
 * @param x int
 * @param y int
 */
public void location(int x, int y) {
	_positionX = x;
	_positionY = y;
}
/**
 * This method was created by a SmartGuide.
 * @param x int
 * @param y int
 */
public void location(Point p) {
	_positionX = p.x;
	_positionY = p.y;
}
}
