package VideoGame;


/**
 * This class was generated by a SmartGuide.
 * 
 */
 import java.util.Vector;
 import java.awt.image.ImageObserver;
public abstract class StaticManagerA implements VideoGame.StaticManagerI {
private Vector _staticCollection;
private ImageObserver _imageObserver;





/**
 * addStatic method comment.
 */
public void addStaticI(StaticI s) {
		_staticCollection.addElement(s);
}
/**
 * drawStatics method comment.
 */
public void drawStatics() {
	int stToHandle = 0;
	while(stToHandle < staticCollection().size()){;
		StaticI st = (StaticI)staticCollection().elementAt(stToHandle);
		st.drawSelf(imageObserver());
		stToHandle ++;
	}//end while	

}
/**
 * This method was created by a SmartGuide.
 * @return ImageObserver
 */
public ImageObserver imageObserver() {
	return _imageObserver;
}
/**
 * This method was created by a SmartGuide.
 * @param ia java.awt.image.ImageObserver
 */
public void imageObserver(ImageObserver ia) {
	_imageObserver = ia;
}
/**
 * removeStatic method comment.
 */
public void removeStaticI(StaticI s) {
}
/**
 * staticCollection method comment.
 */
public java.util.Vector staticCollection() {
	return null;
}
/**
 * staticCollection method comment.
 */
public void staticCollection(java.util.Vector v) {
}
}
