package VideoGame;


/**
 * This interface was generated by a SmartGuide.
 * 
 */
 import java.awt.image.ImageObserver;
public interface StaticI {







/**
 * This method was created by a SmartGuide.
 */
public void drawSelf (ImageObserver ia);
}
