package VideoGame;


/**
 * This class was generated by a SmartGuide.
 * 
 */
 import java.awt.Graphics;
 import java.awt.Point;
public abstract class Transient extends ActorA{
	protected Point _position;
	protected Graphics _graphics;
	protected int _duration;




/**
 * This method was created by a SmartGuide.
 * @param dm VideoGame.DynamicManagerI
 */
public void addSelfTo(DynamicManagerI dm) {
	dm.addDynamic(this);
}
/**
 * This method was created by a SmartGuide.
 * @return int
 */
public int duration() {
	return _duration;
}
/**
 * This method was created by a SmartGuide.
 * @param d int
 */
public void duration (int d ) {
	_duration = d;
}
/**
 * This method was created by a SmartGuide.
 */
public void dynamicManagerI(DynamicManagerI d) {
	graphics(d.graphics());
	super.dynamicManagerI(d);
}
/**
 * This method was created by a SmartGuide.
 * @return java.awt.Graphics
 */
public Graphics graphics() {
	return _graphics;
}
/**
 * This method was created by a SmartGuide.
 */
public void graphics (Graphics g ) {
	_graphics = g;
}
/**
 * This method was created by a SmartGuide.
 */
public void move () {
	super.move();
	duration(duration() -1);
	if(duration() <=0){
		remove();
	}	
}
/**
 * This method was created by a SmartGuide.
 * @return java.awt.Point
 */
public Point position() {
	return _position;
}
/**
 * This method was created by a SmartGuide.
 * @return int
 * @param x int
 * @param y int
 */
public void position (int x, int y ) {
	position().x = x;
	position().y = y;
}
/**
 * This method was created by a SmartGuide.
 * @param p Point
 */
public void position (Point p ) {
	_position = p;
}
/**
 * This method was created by a SmartGuide.
 */
public void positionX (int x ) {
	_position.x = x;
}
/**
 * This method was created by a SmartGuide.
 * @param Y int
 */
public void positionY (int y ) {
	_position.y = y;
}
/**
 * This method was created by a SmartGuide.
 */
public void remove() {
	dynamicManagerI().removeDynamic(this);
}
}
